# Generated by Django 3.1.4 on 2020-12-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20201226_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog', verbose_name='post_image'),
        ),
    ]
